# Generated by Django 4.2.2 on 2023-07-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proudects', '0002_maincategory_category_maincategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mainCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proudects.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'mainCategory__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='proudects.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='products/'),
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
    ]
