# Generated by Django 4.2.2 on 2023-07-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proudects', '0003_alter_category_maincategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'mainCategory__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='proudects.category'),
        ),
    ]
