# Generated by Django 4.2.2 on 2023-07-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proudects', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image/products/download.jpeg', upload_to='products/'),
        ),
    ]
