# Generated by Django 4.2.2 on 2023-07-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proudects', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'mainCategory.set__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='proudects.category'),
        ),
    ]
